In [ ]:
#load and visualize the data
import numpy as np
#read data from text files

with open("/content/drive/MyDrive/deep-learning-v2-pytorch/sentiment-rnn/data/reviews.txt")as f:
  reviews = f.read()

with open("/content/drive/MyDrive/deep-learning-v2-pytorch/sentiment-rnn/data/labels.txt")as f:
  labels = f.read()

In [ ]:
print(reviews[:1000])
print()
print(labels[:20])

bromwell high is a cartoon comedy . it ran at the same time as some other programs about school life  such as  teachers  . my   years in the teaching profession lead me to believe that bromwell high  s satire is much closer to reality than is  teachers  . the scramble to survive financially  the insightful students who can see right through their pathetic teachers  pomp  the pettiness of the whole situation  all remind me of the schools i knew and their students . when i saw the episode in which a student repeatedly tried to burn down the school  i immediately recalled . . . . . . . . . at . . . . . . . . . . high . a classic line inspector i  m here to sack one of your teachers . student welcome to bromwell high . i expect that many adults of my age think that bromwell high is far fetched . what a pity that it isn  t   
story of a man who has unnatural feelings for a pig . starts out with a opening scene that is a terrific example of absurd comedy . a formal orchestra audience is turn

In [ ]:
#get rid of punctuation
from string import punctuation

reviews = reviews.lower() #lowercase, standardize
all_text = "".join([c for c in reviews if c not in punctuation])

#split by new lines and spaces
reviews_split = all_text.split("\n")
all_text = "".join(reviews_split)

#create a list of words
words = all_text.split()

In [ ]:
words[:30]

['bromwell',
 'high',
 'is',
 'a',
 'cartoon',
 'comedy',
 'it',
 'ran',
 'at',
 'the',
 'same',
 'time',
 'as',
 'some',
 'other',
 'programs',
 'about',
 'school',
 'life',
 'such',
 'as',
 'teachers',
 'my',
 'years',
 'in',
 'the',
 'teaching',
 'profession',
 'lead',
 'me']

In [ ]:
#Encoding the words
from collections import Counter

##Build a dictionary that maps words to intergers
counts = Counter(words)
vocab = sorted(counts, key=counts.get, reverse= True)
vocab_to_int = {word: ii for ii, word in enumerate(vocab, 1)}

## use the dict to tokenize each review in revies_split
## store the tokenized reviews in reviews_ints
reviews_ints = []

for review in reviews_split:
  reviews_ints.append([vocab_to_int[word] for word in review.split()])


In [ ]:
#stats about vocabulary
print("Unique words : ", len((vocab_to_int)))
print()

Unique words :  74072



In [ ]:
print("Tokenized review: \n", reviews_ints[:1])

Tokenized review: 
 [[21025, 308, 6, 3, 1050, 207, 8, 2138, 32, 1, 171, 57, 15, 49, 81, 5785, 44, 382, 110, 140, 15, 5194, 60, 154, 9, 1, 4975, 5852, 475, 71, 5, 260, 12, 21025, 308, 13, 1978, 6, 74, 2395, 5, 613, 73, 6, 5194, 1, 24103, 5, 1983, 10166, 1, 5786, 1499, 36, 51, 66, 204, 145, 67, 1199, 5194, 19869, 1, 37442, 4, 1, 221, 883, 31, 2988, 71, 4, 1, 5787, 10, 686, 2, 67, 1499, 54, 10, 216, 1, 383, 9, 62, 3, 1406, 3686, 783, 5, 3483, 180, 1, 382, 10, 1212, 13583, 32, 308, 3, 349, 341, 2913, 10, 143, 127, 5, 7690, 30, 4, 129, 5194, 1406, 2326, 5, 21025, 308, 10, 528, 12, 109, 1448, 4, 60, 543, 102, 12, 21025, 308, 6, 227, 4146, 48, 3, 2211, 12, 8, 215, 23]]


In [ ]:
labels_split = labels.split("\n")
encoded_labels = np.array([1 if label == "positive" else 0 for label in labels_split])

In [ ]:
#outlier review stats
review_lens = Counter([len(x) for x in reviews_ints])
print("Zero_lenght reviews : {}".format(review_lens[0]))
print("Maximum review length : {}".format(max(review_lens)))

Zero_lenght reviews : 1
Maximum review length : 2514


In [ ]:
print("Numer of reviews before removing outliers : ", len(reviews_ints))

## remove any reviews/labels with zero lenght from the reviews_inits list

#get indices of any review with lenght 0
non_zero_idx = [ii for ii, review in enumerate(reviews_ints) if len(review) != 0]

#remove 0 - length reviews and their lables
reviews_ints = [reviews_ints[ii] for ii in non_zero_idx]
encoded_labels = np.array([encoded_labels[ii] for ii in non_zero_idx])

print("Number of reviews after removing outliers : ", len(reviews_ints))

Numer of reviews before removing outliers :  25001
Number of reviews after removing outliers :  25000


In [ ]:
def pad_features(reviews_ints, seq_length):
  """
  Return features of review_ints, where each review is padded with 0's
  or truncated to the input seq_length.

  """

  #getting the correct row x cols shape
  features = np.zeros((len(reviews_ints), seq_length), dtype = int)

  # for each review,
  for i, row in enumerate(reviews_ints):
    features[i, -len(row):] = np.array(row)[:seq_length]

  return features


In [ ]:
#Test the implementation!

seq_length = 200

features = pad_features(reviews_ints, seq_length = seq_length)

assert len(features) == len(reviews_ints), "Features should have as many rows as reviews"
assert len(features[0]) == seq_length, "Each feature should contain seq_lenght values"

print(features[:30, :10])

[[    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [22382    42 46418    15   706 17139  3389    47    77    35]
 [ 4505   505    15     3  3342   162  8312  1652     6  4819]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [   54    10    14   116    60   798   552    71   364     5]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    1   330   578    34     3   162   748  2731     9   325]
 [    9    11 10171  5305  1946   689   444    22   280   673]
 [    0     0     0     0     0     0     0     0     0

In [ ]:
## split data into training, validation, and test data (features and labels, x and y)

split_frac = 0.8

split_idx = int(len(features) * split_frac)
train_x, remaining_x = features[:split_idx], features[split_idx:]
train_y, remaining_y = encoded_labels[:split_idx], encoded_labels[split_idx:]

test_idx = int(len(remaining_x) * 0.5)
val_x, test_x = remaining_x[:test_idx], remaining_x[test_idx:]
val_y, test_y = remaining_y[:test_idx], remaining_y[test_idx:]

## print out the shapes of resultant feature data
print("\t\t\tFeature Shapes:")
print("Train set : \t\t{}".format(train_x.shape),
      "\nValidation set : \t{}".format(val_x.shape),
      "\nTest set: \t{}".format(test_x.shape)
      )

			Feature Shapes:
Train set : 		(20000, 200) 
Validation set : 	(2500, 200) 
Test set: 	(2500, 200)


In [ ]:
#Dataloader and Batching
import torch
from torch.utils.data import TensorDataset, DataLoader

# create Tensor Datasets
train_data = TensorDataset(torch.from_numpy(train_x), torch.from_numpy(train_y))
valid_data = TensorDataset(torch.from_numpy(val_x), torch.from_numpy(val_y))
test_data = TensorDataset(torch.from_numpy(test_x), torch.from_numpy(test_y))

In [ ]:
#dataloaders
batch_size = 50

#make sure the SHUFFLE training data
train_loader = DataLoader(train_data, shuffle = True, batch_size= batch_size)
valid_loader = DataLoader(valid_data, shuffle= True, batch_size = batch_size)
test_loader = DataLoader(test_data, shuffle = True, batch_size = batch_size)

In [ ]:
#obtain one batch of training data for checking
dataiter = iter(train_loader)
sample_x, sample_y = dataiter.next()

print("Sample input size : ", sample_x.size()) #batch_size, seq_length
print("Sample input : \n", sample_x)
print()
print("Sample label size : ", sample_y.size()) #batch_size
print("Sample label : \n", sample_y)

Sample input size :  torch.Size([50, 200])
Sample input : 
 tensor([[  10,   80,   24,  ..., 3738,   17,   55],
        [   0,    0,    0,  ...,    1,  232,  154],
        [   0,    0,    0,  ...,   11, 3898, 1128],
        ...,
        [   3,  184, 1596,  ...,   10,  195,    8],
        [   0,    0,    0,  ...,   19,  120,  544],
        [   0,    0,    0,  ...,  105,    2,  353]])

Sample label size :  torch.Size([50])
Sample label : 
 tensor([0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
        0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
        0, 1])


In [ ]:
#check if GPU is available
train_on_gpu = torch.cuda.is_available()

if (train_on_gpu):
  print("Training on GPU.")
else:
  print("No GPU available, training on CPU.")

Training on GPU.


In [ ]:
import torch.nn as nn

class SentimentRNN(nn.Module):
    """
    The RNN model that will be used to perform Sentiment analysis.
    """

    def __init__(self, vocab_size, output_size, embedding_dim, hidden_dim, n_layers, drop_prob=0.5):
        """
        Initialize the model by setting up the layers.
        """
        super(SentimentRNN, self).__init__()

        self.output_size = output_size
        self.n_layers = n_layers
        self.hidden_dim = hidden_dim

        # embedding and LSTM layers
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, n_layers,
                            dropout=drop_prob, batch_first=True)

        # dropout layer
        self.dropout = nn.Dropout(0.3)

        # linear and sigmoid layers
        self.fc = nn.Linear(hidden_dim, output_size)
        self.sig = nn.Sigmoid()


    def forward(self, x, hidden):
        """
        Perform a forward pass of our model on some input and hidden state.
        """
        batch_size = x.size(0)

        # embeddings and lstm_out
        x = x.long()
        embeds = self.embedding(x)
        lstm_out, hidden = self.lstm(embeds, hidden)

        lstm_out = lstm_out[:, -1, :] # getting the last time step output

        # dropout and fully-connected layer
        out = self.dropout(lstm_out)
        out = self.fc(out)
        # sigmoid function
        sig_out = self.sig(out)

        # return last sigmoid output and hidden state
        return sig_out, hidden


    def init_hidden(self, batch_size):
        ''' Initializes hidden state '''
        # Create two new tensors with sizes n_layers x batch_size x hidden_dim,
        # initialized to zero, for hidden state and cell state of LSTM
        weight = next(self.parameters()).data

        if (train_on_gpu):
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda(),
                  weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda())
        else:
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_(),
                      weight.new(self.n_layers, batch_size, self.hidden_dim).zero_())

        return hidden


In [ ]:
#Instantiate the network

vocab_size = len(vocab_to_int) +1 # +1 for the 0 padding + our word tokens
output_size = 1
embedding_dim = 400
hidden_dim = 256
n_layers = 2

In [ ]:
net = SentimentRNN(vocab_size, output_size, embedding_dim, hidden_dim, n_layers)

print(net)

SentimentRNN(
  (embedding): Embedding(74073, 400)
  (lstm): LSTM(400, 256, num_layers=2, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.3, inplace=False)
  (fc): Linear(in_features=256, out_features=1, bias=True)
  (sig): Sigmoid()
)


In [ ]:
#loss and optimization function s
lr = 0.001

criterion = nn.BCELoss()
optimizer = torch.optim.Adam(net.parameters(), lr = lr)

In [ ]:
# training params

epochs = 4

counter = 0
print_every = 100
clip = 5 #gradient clipping

#move model to GPU, if available
if (train_on_gpu):
  net.cuda()

net.train()

for e in range(epochs):

  h = net.init_hidden(batch_size)

  for inputs, labels in train_loader:
    counter += 1

    if (train_on_gpu):
      inputs, labels = inputs.cuda(), labels.cuda()

    #creating new variables for the hidden state, otherwise
    #we'd backprop through the entire history

    h = tuple([each.data for each in h])

    net.zero_grad()

    output, h = net(inputs, h)

    loss = criterion(output.squeeze(), labels.float())

    loss.backward()

    nn.utils.clip_grad_norm_(net.parameters(), clip)

    optimizer.step()

    if counter % print_every == 0:
      #get validation loss
      val_h = net.init_hidden(batch_size)
      val_losses = []

      net.eval()

      for inputs, labels in valid_loader:

        val_h = tuple([each.data for each in val_h])

        if (train_on_gpu):
          inputs, labels = inputs.cuda(), labels.cuda()

        output, val_h = net(inputs, val_h)

        val_loss = criterion(output.squeeze(), labels.float())

        val_losses.append(val_loss.item())

      net.train()
      print("Epoch: {}/{}...".format(e+1, epochs),
                  "Step: {}...".format(counter),
                  "Loss: {:.6f}...".format(loss.item()),
                  "Val Loss: {:.6f}".format(np.mean(val_losses)))

Epoch: 1/4... Step: 100... Loss: 0.665772... Val Loss: 0.658344
Epoch: 1/4... Step: 200... Loss: 0.691676... Val Loss: 0.604925
Epoch: 1/4... Step: 300... Loss: 0.566442... Val Loss: 0.578297
Epoch: 1/4... Step: 400... Loss: 0.537295... Val Loss: 0.561464
Epoch: 2/4... Step: 500... Loss: 0.497997... Val Loss: 0.531638
Epoch: 2/4... Step: 600... Loss: 0.558878... Val Loss: 0.559426
Epoch: 2/4... Step: 700... Loss: 0.325430... Val Loss: 0.473862
Epoch: 2/4... Step: 800... Loss: 0.401487... Val Loss: 0.504922
Epoch: 3/4... Step: 900... Loss: 0.242682... Val Loss: 0.502825
Epoch: 3/4... Step: 1000... Loss: 0.364459... Val Loss: 0.478515
Epoch: 3/4... Step: 1100... Loss: 0.348377... Val Loss: 0.479493
Epoch: 3/4... Step: 1200... Loss: 0.148307... Val Loss: 0.478637
Epoch: 4/4... Step: 1300... Loss: 0.369976... Val Loss: 0.532164
Epoch: 4/4... Step: 1400... Loss: 0.211883... Val Loss: 0.559018
Epoch: 4/4... Step: 1500... Loss: 0.171344... Val Loss: 0.596756
Epoch: 4/4... Step: 1600... Loss: 

In [ ]:
#Testing

test_losses = []
num_correct = 0

#init hidden state
h = net.init_hidden(batch_size)

net.eval()

#iterate over test data
for inputs, labels in test_loader:

  #creating new variables for the hidden state, otherwise
  #we'd backprop through the entire training history
  h = tuple([each.data for each in h])

  if (train_on_gpu):
    inputs, labels = inputs.cuda(), labels.cuda()

  #get predicted outputs
  output, h = net(inputs, h)

  #calculated loss
  test_loss = criterion(output.squeeze(), labels.float())
  test_losses.append(test_loss.item())

  #convert output probabilities to predicted class (0/1)

  pred = torch.round(output.squeeze())

  correct_tensor = pred.eq(labels.float().view_as(pred))

  correct = np.squeeze(correct_tensor.numpy()) if not train_on_gpu else np.squeeze(correct_tensor.cpu().numpy())

  num_correct += np.sum(correct)

print("Test Loss ; {:.3f}".format(np.mean(test_losses)))

test_acc = num_correct/len(test_loader.dataset)

print("Test accuracy : {:.3f}".format(test_acc))

Test Loss ; 0.462
Test accuracy : 0.820


In [ ]:
# negative test review
test_review_neg = 'The worst movie I have seen; acting was terrible and I want my money back. This movie had bad acting and the dialogue was slow.'


In [ ]:
from string import punctuation

def tokenize_review(test_review):
  test_review = test_review.lower()

  test_text = "".join([c for c in test_review if c not in punctuation])

  test_words = test_text.split()

  test_ints = []
  test_ints.append([vocab_to_int.get(word, 0) for word in test_words])

  return test_ints

test_ints = tokenize_review(test_review_neg)

print(test_ints)

[[1, 247, 18, 10, 28, 108, 113, 14, 388, 2, 10, 181, 60, 273, 144, 11, 18, 68, 76, 113, 2, 1, 410, 14, 539]]


In [ ]:
seq_lenght = 100
features = pad_features(test_ints, seq_length)

print(features)

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   1 247  18  10  28
  108 113  14 388   2  10 181  60 273 144  11  18  68  76 113   2   1 410
   14 539]]


In [ ]:
feature_tensor = torch.from_numpy(features)
print(feature_tensor.size())

torch.Size([1, 200])


In [ ]:
def predict(net, test_review, sequence_length=200):

    net.eval()

    # tokenize review
    test_ints = tokenize_review(test_review)

    # pad tokenized sequence
    seq_length=sequence_length
    features = pad_features(test_ints, seq_length)

    # convert to tensor to pass into your model
    feature_tensor = torch.from_numpy(features)

    batch_size = feature_tensor.size(0)

    # initialize hidden state
    h = net.init_hidden(batch_size)

    if(train_on_gpu):
        feature_tensor = feature_tensor.cuda()

    # get the output from the model
    output, h = net(feature_tensor, h)

    # convert output probabilities to predicted class (0 or 1)
    pred = torch.round(output.squeeze())
    # printing output value, before rounding
    print('Prediction value, pre-rounding: {:.6f}'.format(output.item()))

    # print custom response
    if(pred.item()==1):
        print("Positive review detected!")
    else:
        print("Negative review detected.")


In [ ]:
# call function
seq_length=200 # good to use the length that was trained on

predict(net, test_review_neg, seq_length)

Prediction value, pre-rounding: 0.012903
Negative review detected.


In [ ]:
# positive test review
test_review_pos = 'This movie had the best acting and the dialogue was so good. I loved it.'


In [ ]:
predict(net, test_review_pos, seq_length)

Prediction value, pre-rounding: 0.968728
Positive review detected!
